services:
  frontend:
    image: gitlab-registry.selectel.org/radchenko.v/unspoken:latest
    platform: linux/amd64
    restart: always
    networks:
      - unspoken_network
    depends_on:
      - api
    ports:
      - "80:80"
      - "443:443"
  api:
    build:
      context: .
      dockerfile: api.Dockerfile
    command: /usr/bin/uv run gunicorn unspoken.app:app -w 1 -b :8000 -k uvicorn.workers.UvicornWorker
    restart: always
    ports:
      - "8000:8000"
    env_file:
      - .env
    environment:
      db_user: "unspoken"
      db_password: "changeme"
      db_host: db
      rabbitmq_user: "unspoken"
      rabbitmq_password: "unspoken"
      rabbitmq_host: amqp
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
    volumes:
      - tmp_files_volume:/app/temp_files
      - models_volume:/app/resources/models
    networks:
      - unspoken_network
    depends_on:
      db:
        condition: service_healthy
  db:
    image: postgres:16.1-alpine
    restart: unless-stopped
    environment:
      POSTGRES_DB: "unspoken"
      POSTGRES_USER: "unspoken"
      POSTGRES_PASSWORD: "changeme"
    ports:
      - "5432:5432"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U unspoken -d unspoken" ]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s
    volumes:
      - db:/var/lib/postgresql/data
    networks:
      - unspoken_network
volumes:
  db:
  tmp_files_volume:
  models_volume:
networks:
  unspoken_network:
    name: unspoken
    driver: bridge
    ipam:
      config:
        - subnet: 172.80.0.0/16