services:
  app:
    build: .
    command: /bin/sh -c "uv run uvicorn unspoken.app:app --reload --host ${HOST} --port ${PORT}"    
    develop:
      watch:
        - path: ./unspoken
          target: /app/unspoken
        - path: poetry.lock
          action: rebuild