volumes:
  db:

networks:
  e_net:
    external: true
services:
  frontend:
    profiles:
      - frontend
    image: caddy:2.7.5
    restart: always
    volumes:
      - type: bind
        source: ./Caddyfile
        target: /etc/caddy/Caddyfile
      - type: bind
        source: ./frontend/unspoken/dist
        target: /var/www/app
    depends_on:
      - api
    ports:
      - "80:80"
  api:
    build: .
    command: gunicorn unspoken.app:app -w 1 -b :8000 -k uvicorn.workers.UvicornWorker
    restart: always
    ports:
      - "8000:8000"
    environment:
      db_user: "unspoken"
      db_password: "changeme"
      db_host: db
      rabbitmq_user: "unspoken"
      rabbitmq_password: "unspoken"
      rabbitmq_host: amqp
    volumes:
      - type: bind
        source: ./temp_files
        target: /app/temp_files
    depends_on:
      db:
        condition: service_healthy
  worker-gpu:
    build: .
    restart: always
    command: celery -A unspoken.services.queue.worker.worker worker -Q high_resource_demand -c 1 --loglevel=INFO
    environment:
      db_user: "unspoken"
      db_password: "changeme"
      db_host: db
      rabbitmq_user: "unspoken"
      rabbitmq_password: "unspoken"
      rabbitmq_host: amqp
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [ gpu ]
    volumes:
      - type: bind
        source: ./resources/
        target: /app/resources/
      - type: bind
        source: ./temp_files
        target: /app/temp_files
      - type: bind
        source: /root/.cache/torch/NeMo
        target: /root/.cache/torch/NeMo
    depends_on:
      - amqp
      - api
      - db
    networks:
      - default
      - e_net
  worker:
    build: .
    restart: always
    command: celery -A unspoken.services.queue.worker.worker worker -Q low_resource_demand -c 10 --loglevel=INFO
    environment:
      db_user: "unspoken"
      db_password: "changeme"
      db_host: db
      rabbitmq_user: "unspoken"
      rabbitmq_password: "unspoken"
      rabbitmq_host: amqp
    volumes:
      - type: bind
        source: ./temp_files
        target: /app/temp_files
    depends_on:
      - amqp
      - api
      - db
  db:
    image: postgres:16.1-alpine
    restart: unless-stopped
    environment:
      POSTGRES_DB: "unspoken"
      POSTGRES_USER: "unspoken"
      POSTGRES_PASSWORD: "changeme"
    expose:
      - "5432"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U unspoken -d unspoken" ]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s
    volumes:
      - db:/var/lib/postgresql/data
  amqp:
    image: rabbitmq:3.9.29-management
    hostname: rabbitmq
    environment:
      - RABBITMQ_DEFAULT_USER=unspoken
      - RABBITMQ_DEFAULT_PASS=unspoken
    expose:
      - "5672"
