[tool.poetry]
name = "unspoken"
version = "0.1.0"
description = ""
authors = ["nuclearthinking"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.10"
faster-whisper = "^0.9.0"
sqlalchemy = "^2.0.23"
pydantic = "^2.5.0"
pydantic-settings = "^2.0.3"
fastapi = "^0.104.1"
gunicorn = "^21.2.0"
python-multipart = "^0.0.6"
python-magic = "^0.4.27"
pydub = "^0.25.1"
uvicorn = "^0.24.0.post1"
nvidia-cublas-cu11 = "^11.11.3.6"
nvidia-cudnn-cu11 = "^8.9.6.50"

[tool.poetry.group.dev.dependencies]
ruff = "^0.1.5"
isort = "^5.12.0"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
