[tool.poetry]
name = "unspoken"
version = "0.1.0"
description = ""
authors = ["nuclearthinking"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.10"
faster-whisper = "^0.9.0"
sqlalchemy = "^2.0.23"
pydantic = "^2.5.0"
pydantic-settings = "^2.0.3"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
