"""Update basic model

Revision ID: 842029c9356f
Revises: a74c1f16bbc1
Create Date: 2024-07-13 20:20:26.279225

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '842029c9356f'
down_revision: Union[str, None] = 'a74c1f16bbc1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    op.add_column('temp_file', sa.Column('created_at', sa.DateTime()))
    op.add_column('temp_file', sa.Column('updated_at', sa.DateTime()))
    op.execute('update temp_file set created_at=now(), updated_at=now();')
    op.alter_column('temp_file', column_name='created_at', nullable=False)
    op.alter_column('temp_file', column_name='updated_at', nullable=False)


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('temp_file', 'updated_at')
    op.drop_column('temp_file', 'created_at')
    # ### end Alembic commands ###
