"""Initial migration

Revision ID: a74c1f16bbc1
Revises: 
Create Date: 2024-07-07 22:09:15.251465

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a74c1f16bbc1'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('task', 'wav_file_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('task', sa.Column('wav_file_id', sa.INTEGER(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
